version: 2
jobs:
  test:
    docker:
      - image: circleci/node:4.8.2-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: ./test/e2e.sh:

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          filters:
            branches:
              only: master
